#
# Copyright . All Rights Reserved.
#

version: '3.7'

services:
  cli.clean:
    container_name: cli.clean
#    build:
#      args:
#        FABRIC_VERSION: ${FABRIC_VERSION:-1.4.2}
#      context: ./fabric-tools-extended
    image: ${DOCKER_REGISTRY:-docker.io}/olegabu/fabric-tools-extended:${FABRIC_STARTER_VERSION:-snapshot-0.10-1.4.2}
    working_dir: /etc/hyperledger
    volumes:
    - /var/run/:/host/var/run/
    - ./crypto-config:/etc/hyperledger/crypto-config
    - ./data:/etc/hyperledger/data

